# Generated by Django 4.2.10 on 2024-03-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_pets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pets',
            new_name='Animal',
        ),
    ]
