# Generated by Django 4.2.10 on 2024-03-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_rename_pets_animal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet2',
            options={'managed': False},
        ),
    ]
