# Generated by Django 4.2.10 on 2024-03-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_pet2_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adopted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(default='Female', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(default=15),
        ),
    ]
