# Generated by Django 4.2.10 on 2024-03-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
    ]
