# Generated by Django 4.2.10 on 2024-05-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_customuser_experience_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='type_age',
            field=models.CharField(default='Months', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
