# Generated by Django 4.2.10 on 2024-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_animal_type_age_customuser_type_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
