# Generated by Django 4.2.10 on 2024-05-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_alter_animal_age_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='health',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='idleg',
        ),
    ]
