# Generated by Django 4.2.10 on 2024-05-07 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_remove_animal_health_remove_customuser_idleg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserIdAnimalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('heScore', models.IntegerField(null=True)),
                ('ehScore', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.animal')),
            ],
            options={
                'unique_together': {('customuser', 'idAnimal')},
            },
        ),
    ]
