# Generated by Django 4.2.10 on 2024-05-10 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_customuseridanimalscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('message', models.CharField(max_length=355, null=True)),
                ('isNew', models.BooleanField(default=False, null=True)),
                ('idAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.animal')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver', 'date')},
            },
        ),
    ]
