# Generated by Django 4.2.10 on 2024-05-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_customusermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermessages',
            name='status',
            field=models.CharField(max_length=355, null=True),
        ),
    ]
